switching env

diff --git a/commander_app/install-commander b/commander_app/install-commander
--- a/commander_app/install-commander
+++ b/commander_app/install-commander
@@ -26,6 +26,10 @@ fi
 
 ip=`hostname -I | xargs`
 
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
+
 sudo systemctl stop videowall.service
 
 if ! type "pip" > /dev/null; then
@@ -42,26 +46,38 @@ if ! type "virtualenv" > /dev/null; then
 	sudo /usr/bin/easy_install virtualenv
 fi
 
-if [ ! -d "env/" ]; then
+if [ ! -d "commander_env/" ]; then
 	echo '==='
-	echo "=== Making Python 3 virtual environment in $PWD/env"
+	echo "=== Making Python 3 virtual environment in $PWD/commander_env"
 	echo '==='
 	mkdir env
-	virtualenv -p python3 --no-site-packages env
+	virtualenv -p python3 --no-site-packages commander_env
 else
 	echo '==='
-	echo "=== Python 3 virtual environment already exists in $PWD/env"
+	echo "=== Python 3 virtual environment already exists in $PWD/commander_env"
 	echo '==='
 fi
 
-source env/bin/activate
+if [ -f "commander_env/bin/activate" ]; then
+	echo '==='
+	echo "=== Activating virtual environment with 'source commander_env/bin/activate'"
+	echo '==='
+	source commander_env/bin/activate
+else
+	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/commander_env"
+	echo "Make sure virtualenv is installed and try installing again"
+	exit 1
+fi
 
 echo ' '
 echo '==='
-echo '=== Installing commander Python requirements with pip'
+echo "=== Installing commander Python requirements with 'pip install -r requirements.txt'"
 echo '==='
 pip install -r requirements.txt
 
+echo '==='
+echo "=== Deactivating virtual environment with 'deactivate'"
+echo '==='
 deactivate
 
 # copy 
@@ -69,9 +85,14 @@ echo ' '
 echo '==='
 echo '=== Configuring systemctl in /etc/systemd/system/videowall.service'
 echo '==='
+echo '=== Copying service/videowall.service  ->  /etc/systemd/system/videowall.service'
 sudo cp service/videowall.service /etc/systemd/system/videowall.service
 sudo chmod 664 /etc/systemd/system/videowall.service
+
+echo '=== Reloading system daemons'
 sudo systemctl daemon-reload
+
+echo '=== Enabling and starting videowall.service  (with enable will run at boot)'
 sudo systemctl enable videowall.service
 sudo systemctl start videowall.service
 
@@ -105,8 +126,15 @@ then
 fi
 
 echo ' '
-echo 'Done installing commander server.'
-echo 'The commander server will run at boot.'
-echo "Browse the commander server at http://$ip:8000"
+
+systemctl is-active --quiet videowall.service
+if [ $? -eq 0 ]
+then
+	echo -e "${GREEN}Success${NC}: The commander server is running and will run at boot."
+	echo "Browse the commander server at http://$ip:8000"
+else
+	echo -e "${RED}ERROR${NC}: The commander server failed to install and is not running."
+fi
+echo ' '
 
 
diff --git a/install-pie b/install-pie
--- a/install-pie
+++ b/install-pie
@@ -4,7 +4,7 @@
 # Date: 20180603
 #
 # Purpose: Bash script to install PiE server
-#	1) create a python3 virtual environment in env/
+#	1) create a python3 virtual environment in pie_env/
 #	2) install pie_app/requirements.txt
 #	3) install a systemctl service treadmill.service
 #
@@ -68,36 +68,44 @@ if ! type "virtualenv" > /dev/null; then
 	sudo apt-get -qy install python-virtualenv
 fi
 
-if [ ! -d "env/" ]; then
+if [ ! -d "pie_env/" ]; then
 	echo '==='
-	echo "=== install-pie: Making Python 3 virtual environment in $PWD/env"
+	echo "=== install-pie: Making Python 3 virtual environment in $PWD/pie_env"
 	echo '==='
 	if ! type "virtualenv" > /dev/null; then
 		echo -e 'install-pie: ${RED}ERROR${NC}: DID NOT INSTALL VIRTUALENV -->> ABORTING'
 		exit 0
 	else
-		mkdir env
-		virtualenv -p python3 --no-site-packages env
+		mkdir pie_env
+		virtualenv -p python3 --no-site-packages pie_env
 	fi
 else
 	echo '==='
-	echo "=== install-pie: Python 3 virtual environment already exists in $PWD/env"
+	echo "=== install-pie: Python 3 virtual environment already exists in $PWD/pie_env"
 	echo '==='
 fi
 
-echo '==='
-echo "=== install-pie: Activating Python 3 virtual environment in $PWD/env"
-echo '==='
-source env/bin/activate
 
-echo ' '
+
+if [ -f "pie_env/bin/activate" ]; then
+	echo '==='
+	echo "=== install-pie: Activating Python 3 virtual environment with 'source pie_env/bin/activate'"
+	echo '==='
+	source pie_env/bin/activate
+else
+	echo -e "${RED}ERROR${NC}: Python 3 virtual environment did not install in $PWD/pie_env"
+	echo "Make sure virtualenv is installed and try installing again"
+	exit 1
+fi
+
+
 echo '==='
-echo '=== install-pie: Installing pie_app/requirements.txt'
+echo "=== install-pie: Installing required python libraries with 'pip install -r pie_app/requirements.txt'"
 echo '==='
 pip install -r pie_app/requirements.txt
 
 echo '==='
-echo "=== install-pie: Deactivating Python 3 virtual environment in $PWD/env"
+echo "=== install-pie: Deactivating Python 3 virtual environment with 'deactivate'"
 echo '==='
 deactivate
 
@@ -121,22 +129,20 @@ echo '=== install-pie: Copying admin_app/service/pieadmin.service  ->  /etc/syst
 sudo cp admin_app/service/pieadmin.service /etc/systemd/system/pieadmin.service
 sudo chmod 664 /etc/systemd/system/pieadmin.service
 
-echo '=== install-pie: reloading daemons'
+echo '=== install-pie: reloading system daemons'
 sudo systemctl daemon-reload
 
-echo '=== install-pie: enable and start pieadmin.service'
+echo '=== install-pie: enable and start pieadmin.service (with enable will run at boot)'
 sudo systemctl enable pieadmin.service
 sudo systemctl start pieadmin.service
 
-echo '=== install-pie: enable and start treadmill.service'
+echo '=== install-pie: enable and start treadmill.service (with enable will run at boot)'
 sudo systemctl enable treadmill.service
 sudo systemctl start treadmill.service
 
 #
 # DONE
 #
-
-echo ' '
 
 systemctl is-active --quiet pieadmin.service
 if [ $? -eq 0 ]
